use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ExtensionPointKind {
    Slot,
    ContextMenu,
    Decoration,
    Overlay,
    Screen,
    Command,
    SettingsPanel,
    DockPane,
}

#[derive(Debug, Clone, Copy, Serialize)]
pub struct ExtensionPoint {
    pub id: &'static str,
    pub kind: ExtensionPointKind,
    pub context_schema: &'static str,
    pub contribution_schema: &'static str,
    pub ordering_model: &'static str,
    pub ownership_rules: &'static str,
    pub capabilities: &'static [&'static str],
    pub render_mount_handler: &'static str,
}

pub const EXTENSION_POINTS: &[ExtensionPoint] = &[
    ExtensionPoint {
        id: "main_bar.left",
        kind: ExtensionPointKind::Slot,
        context_schema: "MainBarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:main_bar"],
        render_mount_handler: "RegionMountRegistry::MainBar",
    },
    ExtensionPoint {
        id: "main_bar.center",
        kind: ExtensionPointKind::Slot,
        context_schema: "MainBarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:main_bar"],
        render_mount_handler: "RegionMountRegistry::MainBar",
    },
    ExtensionPoint {
        id: "main_bar.right",
        kind: ExtensionPointKind::Slot,
        context_schema: "MainBarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:main_bar"],
        render_mount_handler: "RegionMountRegistry::MainBar",
    },
    ExtensionPoint {
        id: "tab_bar.left",
        kind: ExtensionPointKind::Slot,
        context_schema: "TabBarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:tab_bar"],
        render_mount_handler: "RegionMountRegistry::TabBar",
    },
    ExtensionPoint {
        id: "tab_bar.right",
        kind: ExtensionPointKind::Slot,
        context_schema: "TabBarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:tab_bar"],
        render_mount_handler: "RegionMountRegistry::TabBar",
    },
    ExtensionPoint {
        id: "repository.sidebar.top",
        kind: ExtensionPointKind::Slot,
        context_schema: "RepositorySidebarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:repository"],
        render_mount_handler: "RegionMountRegistry::Repository",
    },
    ExtensionPoint {
        id: "repository.sidebar.bottom",
        kind: ExtensionPointKind::Slot,
        context_schema: "RepositorySidebarContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:repository"],
        render_mount_handler: "RegionMountRegistry::Repository",
    },
    ExtensionPoint {
        id: "repository.graph.top",
        kind: ExtensionPointKind::Slot,
        context_schema: "RepositoryGraphContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:repository"],
        render_mount_handler: "RegionMountRegistry::Repository",
    },
    ExtensionPoint {
        id: "repository.graph.bottom",
        kind: ExtensionPointKind::Slot,
        context_schema: "RepositoryGraphContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:repository"],
        render_mount_handler: "RegionMountRegistry::Repository",
    },
    ExtensionPoint {
        id: "repository.details.top",
        kind: ExtensionPointKind::Slot,
        context_schema: "RepositoryDetailsContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:repository"],
        render_mount_handler: "RegionMountRegistry::Repository",
    },
    ExtensionPoint {
        id: "repository.details.bottom",
        kind: ExtensionPointKind::Slot,
        context_schema: "RepositoryDetailsContext",
        contribution_schema: "LeviathanSlotSpec",
        ordering_model: "priority ascending, then owner/id",
        ownership_rules: "owned by full SlotAddress(plugin, region, container, id)",
        capabilities: &["ui:region:repository"],
        render_mount_handler: "RegionMountRegistry::Repository",
    },
    ExtensionPoint {
        id: "repository.diff.context_menu",
        kind: ExtensionPointKind::ContextMenu,
        context_schema: "RepositoryDiffContext",
        contribution_schema: "LeviathanContextMenuItem",
        ordering_model: "priority ascending, then plugin/id",
        ownership_rules: "owned by plugin + point id + item id",
        capabilities: &["ui:context_menu:repository.diff.context_menu"],
        render_mount_handler: "ExtensionRegistry::context_menu_items",
    },
    ExtensionPoint {
        id: "repository.graph.context_menu",
        kind: ExtensionPointKind::ContextMenu,
        context_schema: "RepositoryGraphContext",
        contribution_schema: "LeviathanContextMenuItem",
        ordering_model: "priority ascending, then plugin/id",
        ownership_rules: "owned by plugin + point id + item id",
        capabilities: &["ui:context_menu:repository.graph.context_menu"],
        render_mount_handler: "ExtensionRegistry::context_menu_items",
    },
    ExtensionPoint {
        id: "repository.graph.row_badge",
        kind: ExtensionPointKind::Decoration,
        context_schema: "RepositoryGraphRowContext",
        contribution_schema: "LeviathanGraphDecorationContribution",
        ordering_model: "static rows by commit/plugin/id; providers in plugin/id order",
        ownership_rules: "owned by plugin + point id + decoration/provider id",
        capabilities: &["ui:decoration:graph"],
        render_mount_handler: "ExtensionRegistry::graph_decorations_for",
    },
    ExtensionPoint {
        id: "repository.diff.line_gutter",
        kind: ExtensionPointKind::Decoration,
        context_schema: "RepositoryDiffLineContext",
        contribution_schema: "LeviathanDiffDecorationContribution",
        ordering_model: "static rows by plugin/id; providers in plugin/id order",
        ownership_rules: "owned by plugin + point id + decoration/provider id",
        capabilities: &["ui:decoration:diff"],
        render_mount_handler: "ExtensionRegistry::diff_decorations_for_line",
    },
    ExtensionPoint {
        id: "overlays",
        kind: ExtensionPointKind::Overlay,
        context_schema: "OverlayContext",
        contribution_schema: "LeviathanOverlaySpec",
        ordering_model: "priority descending, then plugin/id",
        ownership_rules: "owned by plugin + overlay id",
        capabilities: &["ui:overlay"],
        render_mount_handler: "ExtensionRegistry::overlays",
    },
    ExtensionPoint {
        id: "screens",
        kind: ExtensionPointKind::Screen,
        context_schema: "ScreenContext",
        contribution_schema: "LeviathanScreenSpec",
        ordering_model: "selected explicitly by command/user action",
        ownership_rules: "owned by plugin + screen id",
        capabilities: &["ui:screen"],
        render_mount_handler: "PluginHost::open_screen",
    },
    ExtensionPoint {
        id: "commands",
        kind: ExtensionPointKind::Command,
        context_schema: "LeviathanUiContext",
        contribution_schema: "LeviathanCommandSpec",
        ordering_model:
            "registry order by plugin/name; palette/keymap projections sort independently",
        ownership_rules: "owned by plugin + command id",
        capabilities: &[],
        render_mount_handler: "CommandRegistry",
    },
    ExtensionPoint {
        id: "settings.panel",
        kind: ExtensionPointKind::SettingsPanel,
        context_schema: "SettingsContext",
        contribution_schema: "LeviathanSettingsSchema",
        ordering_model: "plugin id",
        ownership_rules: "owned by plugin settings storage",
        capabilities: &[],
        render_mount_handler: "SettingsSummary",
    },
    ExtensionPoint {
        id: "dock.pane",
        kind: ExtensionPointKind::DockPane,
        context_schema: "DockPanelContext",
        contribution_schema: "LeviathanDockPanelSpec",
        ordering_model: "area order, then plugin/id",
        ownership_rules: "owned by plugin + dock panel id",
        capabilities: &["ui:dock"],
        render_mount_handler: "DockManager",
    },
];

pub fn extension_point(id: &str) -> Option<&'static ExtensionPoint> {
    EXTENSION_POINTS.iter().find(|point| point.id == id)
}
