use super::schema::*;

#[path = "function_common.rs"]
mod function_common;
#[path = "function_git.rs"]
mod function_git;
#[path = "function_io.rs"]
mod function_io;
#[path = "function_platform.rs"]
mod function_platform;
#[path = "function_ui.rs"]
mod function_ui;

use function_common::V1;
use function_git::{GIT_FUNCTIONS, REPOSITORY_FUNCTIONS};
use function_io::{ENV_FUNCTIONS, FS_FUNCTIONS};
use function_platform::{
    ASYNC_FUNCTIONS, AUTOCMD_FUNCTIONS, COMMAND_FUNCTIONS, HEALTH_FUNCTIONS, KEYMAP_FUNCTIONS,
    PERSIST_FUNCTIONS, RUNTIME_FUNCTIONS, SECRETS_FUNCTIONS, SERVICES_FUNCTIONS,
    SETTINGS_FUNCTIONS, TAB_REGISTRY_FUNCTIONS, TIMER_FUNCTIONS,
};
use function_ui::{API_FUNCTIONS, ROOT_FUNCTIONS, UI_FUNCTIONS, UI_REGIONS_FUNCTIONS};

pub const API_MODULES: &[ApiModule] = &[
    ApiModule {
        name: "root",
        table: "leviathan",
        version: V1,
        doc: "Root host API table.",
        functions: ROOT_FUNCTIONS,
        events: &[],
        types: &["leviathan"],
        capabilities: &[],
    },
    ApiModule {
        name: "api",
        table: "leviathan.api",
        version: V1,
        doc: "Descriptor and scheduling APIs.",
        functions: API_FUNCTIONS,
        events: &[],
        types: &["leviathan.api", "LeviathanAutocmdOpts", "LeviathanAutocmdEvent"],
        capabilities: &[],
    },
    ApiModule {
        name: "command",
        table: "leviathan.command",
        version: V1,
        doc: "Typed command registry and palette dispatch.",
        functions: COMMAND_FUNCTIONS,
        events: &["CommandExecuted"],
        types: &[
            "leviathan.command",
            "LeviathanCommandSpec",
            "LeviathanCommandArg",
            "LeviathanCommandSummary",
        ],
        capabilities: &[],
    },
    ApiModule {
        name: "keymap",
        table: "leviathan.keymap",
        version: V1,
        doc: "Context-aware keymap registry.",
        functions: KEYMAP_FUNCTIONS,
        events: &["KeymapTriggered"],
        types: &[
            "leviathan.keymap",
            "LeviathanKeymapOpts",
            "LeviathanKeymapSummary",
            "LeviathanKeymapConflictRef",
        ],
        capabilities: &[],
    },
    ApiModule {
        name: "autocmd",
        table: "leviathan.autocmd",
        version: V1,
        doc: "Autocmd group and typed-event registration namespace.",
        functions: AUTOCMD_FUNCTIONS,
        events: &[
            "AppStarted",
            "AppWillQuit",
            "RepositoryOpened",
            "RepositoryClosed",
            "RepositoryChanged",
            "RefsChanged",
            "HeadChanged",
            "BranchChanged",
            "CommitSelected",
            "CommitListChanged",
            "DiffLoaded",
            "WorktreeChanged",
            "FetchStarted",
            "FetchFinished",
            "PushStarted",
            "PushFinished",
            "TabAdded",
            "TabRemoved",
            "TabSelected",
            "TabMoved",
            "ThemeChanged",
            "SettingsChanged",
            "CommandExecuted",
            "KeymapTriggered",
        ],
        types: &[
            "leviathan.autocmd",
            "LeviathanAutocmdOpts",
            "LeviathanAutocmdGroupOpts",
            "LeviathanAutocmdEvent",
        ],
        capabilities: &[],
    },
    ApiModule {
        name: "ui",
        table: "leviathan.ui",
        version: V1,
        doc: "UI region and plugin screen APIs.",
        functions: UI_FUNCTIONS,
        events: &[],
        types: &[
            "leviathan.ui",
            "LeviathanScreenSpec",
            "LeviathanSlotSpec",
            "LeviathanSlotTarget",
        ],
        capabilities: &[],
    },
    ApiModule {
        name: "ui.regions",
        table: "leviathan.ui.regions",
        version: V1,
        doc: "Descriptor-backed region slot API.",
        functions: UI_REGIONS_FUNCTIONS,
        events: &[],
        types: &["leviathan.ui.regions", "LeviathanSlotSpec", "LeviathanSlotTarget"],
        capabilities: &[],
    },
    ApiModule {
        name: "fs",
        table: "leviathan.fs",
        version: V1,
        doc: "Filesystem and path helper APIs.",
        functions: FS_FUNCTIONS,
        events: &[],
        types: &["leviathan.fs", "LeviathanFsEntry"],
        capabilities: &["fs:read", "fs:write:*"],
    },
    ApiModule {
        name: "env",
        table: "leviathan.env",
        version: V1,
        doc: "Process environment access.",
        functions: ENV_FUNCTIONS,
        events: &[],
        types: &["leviathan.env"],
        capabilities: &["env"],
    },
    ApiModule {
        name: "repository",
        table: "leviathan.repository",
        version: V1,
        doc: "Active repository snapshot plus typed read APIs.",
        functions: REPOSITORY_FUNCTIONS,
        events: &["BranchChanged", "RefsChanged", "HeadChanged", "CommitListChanged"],
        types: &[
            "leviathan.repository",
            "LeviathanLocalBranch",
            "LeviathanRemoteBranch",
            "LeviathanTag",
        ],
        capabilities: &[
            "git:read:status",
            "git:read:log",
            "git:read:diff",
            "git:read:show",
            "git:read:blame",
        ],
    },
    ApiModule {
        name: "git",
        table: "leviathan.git",
        version: V1,
        doc: "Typed Git write APIs. All routes are capability-checked, audited, and gated by the host's confirmation policy when destructive.",
        functions: GIT_FUNCTIONS,
        events: &[
            "HeadChanged",
            "BranchChanged",
            "RefsChanged",
            "FetchStarted",
            "FetchFinished",
            "PushStarted",
            "PushFinished",
        ],
        types: &["leviathan.git"],
        capabilities: &[
            "git:write:checkout",
            "git:write:branch",
            "git:write:tag",
            "git:write:commit",
            "git:write:stash",
            "git:write:reset",
            "git:write:fetch",
            "git:write:push",
            "git:write:merge",
            "git:write:rebase",
        ],
    },
    ApiModule {
        name: "tab_registry",
        table: "leviathan.tab_registry",
        version: V1,
        doc: "Read-only tab snapshot plus queued tab mutation APIs.",
        functions: TAB_REGISTRY_FUNCTIONS,
        events: &["TabAdded", "TabRemoved", "TabMoved", "TabSelected"],
        types: &["leviathan.tab_registry", "LeviathanTab"],
        capabilities: &[],
    },
    ApiModule {
        name: "services",
        table: "leviathan.services",
        version: V1,
        doc: "Inter-plugin service registry APIs.",
        functions: SERVICES_FUNCTIONS,
        events: &[],
        types: &["leviathan.services"],
        capabilities: &[],
    },
    ApiModule {
        name: "persist",
        table: "leviathan.persist",
        version: V1,
        doc: "Versioned per-plugin persistence APIs.",
        functions: PERSIST_FUNCTIONS,
        events: &[],
        types: &[
            "leviathan.persist",
            "LeviathanPersistStore",
            "LeviathanPersistOpenOpts",
        ],
        capabilities: &[],
    },
    ApiModule {
        name: "settings",
        table: "leviathan.settings",
        version: V1,
        doc: "Schema-backed plugin settings APIs.",
        functions: SETTINGS_FUNCTIONS,
        events: &["SettingsChanged"],
        types: &["leviathan.settings", "LeviathanSettingsSchema"],
        capabilities: &[],
    },
    ApiModule {
        name: "secrets",
        table: "leviathan.secrets",
        version: V1,
        doc: "Plugin-local secret APIs. Devtools exposes metadata only.",
        functions: SECRETS_FUNCTIONS,
        events: &[],
        types: &["leviathan.secrets"],
        capabilities: &[],
    },
    ApiModule {
        name: "health",
        table: "leviathan.health",
        version: V1,
        doc: "Plugin health-check APIs.",
        functions: HEALTH_FUNCTIONS,
        events: &[],
        types: &["leviathan.health", "LeviathanHealthContext"],
        capabilities: &[],
    },
    ApiModule {
        name: "runtime",
        table: "leviathan.runtime",
        version: V1,
        doc: "Runtimepath, module-loader, and after-directory introspection.",
        functions: RUNTIME_FUNCTIONS,
        events: &[],
        types: &[
            "leviathan.runtime",
            "LeviathanRuntimePathEntry",
            "LeviathanRuntimeMatch",
            "LeviathanRuntimeModuleGraphEntry",
        ],
        capabilities: &[],
    },
    ApiModule {
        name: "async",
        table: "leviathan.async",
        version: V1,
        doc: "Host-managed background workers.",
        functions: ASYNC_FUNCTIONS,
        events: &[],
        types: &[
            "leviathan.async",
            "LeviathanJobHandle",
            "LeviathanJobContext",
        ],
        capabilities: &["async:spawn"],
    },
    ApiModule {
        name: "timer",
        table: "leviathan.timer",
        version: V1,
        doc: "One-shot and repeating timers.",
        functions: TIMER_FUNCTIONS,
        events: &[],
        types: &["leviathan.timer", "LeviathanTimerHandle"],
        capabilities: &["timer:create"],
    },
];
