use super::super::schema::*;
use super::function_common::*;

const FS_READ_CAP: &[&str] = &["fs:read"];
const FS_WRITE_CAP: &[&str] = &["fs:write:*"];
const FS_READ_WRITE_CAP: &[&str] = &["fs:read", "fs:write:*"];
const ENV_CAP: &[&str] = &["env"];

pub(super) const FS_FUNCTIONS: &[ApiFunction] = &[
    ApiFunction {
        path: "leviathan.fs.read_file",
        name: "read_file",
        since: "1.0",
        compatibility: "v1",
        doc: "Read UTF-8 file contents. Returns content or (nil, err).",
        params: STRING_PATH,
        returns: NILABLE_STRING_ERR_RET,
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.read_lines",
        name: "read_lines",
        since: "1.0",
        compatibility: "v1",
        doc: "Read a UTF-8 file as an array of lines.",
        params: STRING_PATH,
        returns: &[
            ApiReturn {
                lua_type: "string[]|nil",
                doc: "Lines on success.",
            },
            ApiReturn {
                lua_type: "string|nil",
                doc: "Error message on failure.",
            },
        ],
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.write_file",
        name: "write_file",
        since: "1.0",
        compatibility: "v1",
        doc: "Write content to a file, replacing existing contents.",
        params: &[
            ApiParam {
                name: "path",
                lua_type: "string",
                required: true,
                doc: "Target path.",
            },
            ApiParam {
                name: "content",
                lua_type: "string",
                required: true,
                doc: "UTF-8 content.",
            },
        ],
        returns: OK_ERR_RET,
        capabilities: FS_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.append_file",
        name: "append_file",
        since: "1.0",
        compatibility: "v1",
        doc: "Append content to a file, creating it when absent.",
        params: &[
            ApiParam {
                name: "path",
                lua_type: "string",
                required: true,
                doc: "Target path.",
            },
            ApiParam {
                name: "content",
                lua_type: "string",
                required: true,
                doc: "UTF-8 content.",
            },
        ],
        returns: OK_ERR_RET,
        capabilities: FS_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.delete",
        name: "delete",
        since: "1.0",
        compatibility: "v1",
        doc: "Delete a file or directory tree.",
        params: STRING_PATH,
        returns: OK_ERR_RET,
        capabilities: FS_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.mkdir",
        name: "mkdir",
        since: "1.0",
        compatibility: "v1",
        doc: "Create a directory and missing parents.",
        params: STRING_PATH,
        returns: OK_ERR_RET,
        capabilities: FS_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.copy",
        name: "copy",
        since: "1.0",
        compatibility: "v1",
        doc: "Copy a regular file.",
        params: &[
            ApiParam {
                name: "src",
                lua_type: "string",
                required: true,
                doc: "Source path.",
            },
            ApiParam {
                name: "dst",
                lua_type: "string",
                required: true,
                doc: "Destination path.",
            },
        ],
        returns: OK_ERR_RET,
        capabilities: FS_READ_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.rename",
        name: "rename",
        since: "1.0",
        compatibility: "v1",
        doc: "Move or rename a path.",
        params: &[
            ApiParam {
                name: "src",
                lua_type: "string",
                required: true,
                doc: "Source path.",
            },
            ApiParam {
                name: "dst",
                lua_type: "string",
                required: true,
                doc: "Destination path.",
            },
        ],
        returns: OK_ERR_RET,
        capabilities: FS_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.touch",
        name: "touch",
        since: "1.0",
        compatibility: "v1",
        doc: "Create a file or update its modification time.",
        params: STRING_PATH,
        returns: OK_ERR_RET,
        capabilities: FS_WRITE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.read_link",
        name: "read_link",
        since: "1.0",
        compatibility: "v1",
        doc: "Read a symlink target without following it.",
        params: STRING_PATH,
        returns: NILABLE_STRING_ERR_RET,
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.list_dir",
        name: "list_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "List directory entries sorted with directories first.",
        params: STRING_PATH,
        returns: &[
            ApiReturn {
                lua_type: "LeviathanFsEntry[]|nil",
                doc: "Directory entries on success.",
            },
            ApiReturn {
                lua_type: "string|nil",
                doc: "Error message on failure.",
            },
        ],
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.exists",
        name: "exists",
        since: "1.0",
        compatibility: "v1",
        doc: "Return whether a path exists.",
        params: STRING_PATH,
        returns: BOOL_RET,
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.is_file",
        name: "is_file",
        since: "1.0",
        compatibility: "v1",
        doc: "Return whether a path is a regular file.",
        params: STRING_PATH,
        returns: BOOL_RET,
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.is_dir",
        name: "is_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "Return whether a path is a directory.",
        params: STRING_PATH,
        returns: BOOL_RET,
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.is_symlink",
        name: "is_symlink",
        since: "1.0",
        compatibility: "v1",
        doc: "Return whether a path itself is a symlink.",
        params: STRING_PATH,
        returns: BOOL_RET,
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.size",
        name: "size",
        since: "1.0",
        compatibility: "v1",
        doc: "Return symlink metadata size in bytes.",
        params: STRING_PATH,
        returns: &[
            ApiReturn {
                lua_type: "integer|nil",
                doc: "Byte size on success.",
            },
            ApiReturn {
                lua_type: "string|nil",
                doc: "Error message on failure.",
            },
        ],
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.modified",
        name: "modified",
        since: "1.0",
        compatibility: "v1",
        doc: "Return modification time as Unix seconds.",
        params: STRING_PATH,
        returns: &[
            ApiReturn {
                lua_type: "number|nil",
                doc: "Unix timestamp on success.",
            },
            ApiReturn {
                lua_type: "string|nil",
                doc: "Error message on failure.",
            },
        ],
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.metadata",
        name: "metadata",
        since: "1.0",
        compatibility: "v1",
        doc: "Return metadata shaped like a single list_dir entry.",
        params: STRING_PATH,
        returns: &[
            ApiReturn {
                lua_type: "LeviathanFsEntry|nil",
                doc: "Entry metadata on success.",
            },
            ApiReturn {
                lua_type: "string|nil",
                doc: "Error message on failure.",
            },
        ],
        capabilities: FS_READ_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.is_absolute",
        name: "is_absolute",
        since: "1.0",
        compatibility: "v1",
        doc: "Return whether a path string is absolute.",
        params: STRING_PATH,
        returns: BOOL_RET,
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.parent",
        name: "parent",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the parent path string, or nil.",
        params: STRING_PATH,
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Parent path.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.basename",
        name: "basename",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the final path component, or nil.",
        params: STRING_PATH,
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "File name.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.stem",
        name: "stem",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the file stem, or nil.",
        params: STRING_PATH,
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "File stem.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.extension",
        name: "extension",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the final file extension, or nil.",
        params: STRING_PATH,
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "File extension.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.join",
        name: "join",
        since: "1.0",
        compatibility: "v1",
        doc: "Join two path strings.",
        params: &[
            ApiParam {
                name: "a",
                lua_type: "string",
                required: true,
                doc: "Base path.",
            },
            ApiParam {
                name: "b",
                lua_type: "string",
                required: true,
                doc: "Child path.",
            },
        ],
        returns: &[ApiReturn {
            lua_type: "string",
            doc: "Joined path.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.relative_to",
        name: "relative_to",
        since: "1.0",
        compatibility: "v1",
        doc: "Return path relative to base when path is under base.",
        params: &[
            ApiParam {
                name: "path",
                lua_type: "string",
                required: true,
                doc: "Path to rewrite.",
            },
            ApiParam {
                name: "base",
                lua_type: "string",
                required: true,
                doc: "Base directory.",
            },
        ],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Relative path or nil.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.with_extension",
        name: "with_extension",
        since: "1.0",
        compatibility: "v1",
        doc: "Return path with its final extension replaced.",
        params: &[
            ApiParam {
                name: "path",
                lua_type: "string",
                required: true,
                doc: "Path to rewrite.",
            },
            ApiParam {
                name: "ext",
                lua_type: "string",
                required: true,
                doc: "New extension.",
            },
        ],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Rewritten path or nil.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.with_file_name",
        name: "with_file_name",
        since: "1.0",
        compatibility: "v1",
        doc: "Return path with its final component replaced.",
        params: &[
            ApiParam {
                name: "path",
                lua_type: "string",
                required: true,
                doc: "Path to rewrite.",
            },
            ApiParam {
                name: "name",
                lua_type: "string",
                required: true,
                doc: "Replacement file name.",
            },
        ],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Rewritten path or nil.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.cwd",
        name: "cwd",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the process current working directory.",
        params: &[],
        returns: NILABLE_STRING_ERR_RET,
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.home",
        name: "home",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the user home directory, or nil.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Home directory.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.temp_dir",
        name: "temp_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the process temporary directory.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "string",
            doc: "Temporary directory.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.config_dir",
        name: "config_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the standard user config directory, or nil.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Config directory.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.cache_dir",
        name: "cache_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the standard user cache directory, or nil.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Cache directory.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.data_dir",
        name: "data_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the standard user data directory, or nil.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "Data directory.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.state_dir",
        name: "state_dir",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the standard user state directory, or nil.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "string|nil",
            doc: "State directory.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.fs.canonicalize",
        name: "canonicalize",
        since: "1.0",
        compatibility: "v1",
        doc: "Resolve a path to an absolute canonical path.",
        params: STRING_PATH,
        returns: NILABLE_STRING_ERR_RET,
        capabilities: &[],
        validation: ApiValidation {
            args: &["path must be a string"],
            returns: &["string|nil", "string|nil"],
            notes: &["Canonicalize is ungated even though it reads filesystem state."],
        },
    },
    ApiFunction {
        path: "leviathan.fs.watch",
        name: "watch",
        since: "1.0",
        compatibility: "v1",
        doc: "Watch a path for filesystem changes and dispatch events to a callback.",
        params: &[
            ApiParam {
                name: "path",
                lua_type: "string",
                required: true,
                doc: "Path to watch (file or directory).",
            },
            ApiParam {
                name: "opts",
                lua_type: "LeviathanFsWatchOpts|nil",
                required: false,
                doc: "{ recursive = bool }.",
            },
            ApiParam {
                name: "callback",
                lua_type: "fun(event: LeviathanFsWatchEvent)",
                required: true,
                doc: "Callback invoked on each event.",
            },
        ],
        returns: &[ApiReturn {
            lua_type: "LeviathanFsWatchHandle",
            doc: "Handle with `:cancel()` method.",
        }],
        capabilities: &["fs:watch"],
        validation: ApiValidation {
            args: &["path must resolve under a granted fs:watch scope"],
            returns: &["FsWatchHandle"],
            notes: &[
                "Cancel via the returned handle; the host also cancels on plugin reload/unload.",
            ],
        },
    },
];

pub(super) const ENV_FUNCTIONS: &[ApiFunction] = &[
    ApiFunction {
        path: "leviathan.env.get",
        name: "get",
        since: "1.0",
        compatibility: "v1",
        doc: "Read an environment variable. Returns (value, nil), (nil, nil), or (nil, err).",
        params: STRING_NAME,
        returns: NILABLE_STRING_ERR_RET,
        capabilities: ENV_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.env.list",
        name: "list",
        since: "1.0",
        compatibility: "v1",
        doc: "List UTF-8 environment variables as a name/value table.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "table<string,string>",
            doc: "Environment map.",
        }],
        capabilities: ENV_CAP,
        validation: NO_VALIDATION,
    },
];
