use super::super::schema::*;
use super::function_common::*;

const GIT_READ_STATUS_CAP: &[&str] = &["git:read:status"];
const GIT_READ_LOG_CAP: &[&str] = &["git:read:log"];
const GIT_READ_DIFF_CAP: &[&str] = &["git:read:diff"];
const GIT_READ_SHOW_CAP: &[&str] = &["git:read:show"];
const GIT_READ_BLAME_CAP: &[&str] = &["git:read:blame"];
const GIT_WRITE_CHECKOUT_CAP: &[&str] = &["git:write:checkout"];
const GIT_WRITE_BRANCH_CAP: &[&str] = &["git:write:branch"];
const GIT_WRITE_TAG_CAP: &[&str] = &["git:write:tag"];
const GIT_WRITE_COMMIT_CAP: &[&str] = &["git:write:commit"];
const GIT_WRITE_STASH_CAP: &[&str] = &["git:write:stash"];
const GIT_WRITE_RESET_CAP: &[&str] = &["git:write:reset"];
const GIT_WRITE_FETCH_CAP: &[&str] = &["git:write:fetch"];
const GIT_WRITE_PUSH_CAP: &[&str] = &["git:write:push"];
const GIT_WRITE_MERGE_CAP: &[&str] = &["git:write:merge"];
const GIT_WRITE_REBASE_CAP: &[&str] = &["git:write:rebase"];

pub(super) const REPOSITORY_FUNCTIONS: &[ApiFunction] = &[
    ApiFunction {
        path: "leviathan.repository.current",
        name: "current",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the cached `leviathan.repository` snapshot table for the active repo.",
        params: &[],
        returns: &[ApiReturn {
            lua_type: "table",
            doc: "Active repository snapshot.",
        }],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.refs",
        name: "refs",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the active repository's typed refs (locals, remotes, tags). Returns (refs, nil) or (nil, err).",
        params: &[],
        returns: &[
            ApiReturn { lua_type: "table|nil", doc: "Refs snapshot on success." },
            ApiReturn { lua_type: "string|nil", doc: "Error message on failure." },
        ],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.head",
        name: "head",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the active repository's HEAD info: { hash, ref, detached }.",
        params: &[],
        returns: &[
            ApiReturn { lua_type: "table|nil", doc: "HEAD snapshot on success." },
            ApiReturn { lua_type: "string|nil", doc: "Error message on failure." },
        ],
        capabilities: &[],
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.status",
        name: "status",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the working-tree status: { staged[], unstaged[], conflicted[] }.",
        params: &[],
        returns: &[
            ApiReturn { lua_type: "table|nil", doc: "Status snapshot on success." },
            ApiReturn { lua_type: "string|nil", doc: "Error message on failure." },
        ],
        capabilities: GIT_READ_STATUS_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.commits",
        name: "commits",
        since: "1.0",
        compatibility: "v1",
        doc: "Return up to `limit` commits from the active repository. Each entry: { hash, summary, author, timestamp, parents }.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: false,
            doc: "Options table: { limit = 100, rev = \"HEAD\" }.",
        }],
        returns: &[
            ApiReturn { lua_type: "table[]|nil", doc: "Commit list on success." },
            ApiReturn { lua_type: "string|nil", doc: "Error message on failure." },
        ],
        capabilities: GIT_READ_LOG_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.diff",
        name: "diff",
        since: "1.0",
        compatibility: "v1",
        doc: "Return per-file diff for `commit`. Each entry: { path, status, additions, deletions }.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "Options table: { commit = hash }.",
        }],
        returns: &[
            ApiReturn { lua_type: "table[]|nil", doc: "Diff snapshot on success." },
            ApiReturn { lua_type: "string|nil", doc: "Error message on failure." },
        ],
        capabilities: GIT_READ_DIFF_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.file_at",
        name: "file_at",
        since: "1.0",
        compatibility: "v1",
        doc: "Return the file at a given commit/path as { lines = string[] } (per-line diff content).",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "Options table: { commit = hash, path = \"src/main.rs\" }.",
        }],
        returns: &[
            ApiReturn { lua_type: "table|nil", doc: "File-at-commit snapshot on success." },
            ApiReturn { lua_type: "string|nil", doc: "Error message on failure." },
        ],
        capabilities: GIT_READ_SHOW_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.repository.blame",
        name: "blame",
        since: "1.0",
        compatibility: "v1",
        doc: "Blame is not yet wired through the host gateway. Returns (nil, \"unsupported\").",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "Options table: { path = \"src/main.rs\", line_range = {start,end} }.",
        }],
        returns: &[
            ApiReturn { lua_type: "nil", doc: "Always nil." },
            ApiReturn { lua_type: "string", doc: "Error message." },
        ],
        capabilities: GIT_READ_BLAME_CAP,
        validation: NO_VALIDATION,
    },
];

pub(super) const GIT_FUNCTIONS: &[ApiFunction] = &[
    ApiFunction {
        path: "leviathan.git.checkout",
        name: "checkout",
        since: "1.0",
        compatibility: "v1",
        doc: "Check out `ref`. Returns (true, nil) on enqueue + success, (false, err) otherwise.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ ref = \"main\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_CHECKOUT_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.create_branch",
        name: "create_branch",
        since: "1.0",
        compatibility: "v1",
        doc: "Create branch `name` at `start_point` (defaults to HEAD).",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ name = \"topic\", start_point = \"HEAD\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_BRANCH_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.delete_branch",
        name: "delete_branch",
        since: "1.0",
        compatibility: "v1",
        doc: "Delete branch `name`. `force = true` requires destructive confirmation.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ name = \"topic\", force = false }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_BRANCH_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.create_tag",
        name: "create_tag",
        since: "1.0",
        compatibility: "v1",
        doc: "Create lightweight tag `name` at `target` (defaults to HEAD).",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ name = \"v1.2.3\", target = \"HEAD\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_TAG_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.delete_tag",
        name: "delete_tag",
        since: "1.0",
        compatibility: "v1",
        doc: "Delete tag `name` locally. Destructive — requires confirmation.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ name = \"v1.2.3\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_TAG_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.commit",
        name: "commit",
        since: "1.0",
        compatibility: "v1",
        doc: "Commit currently-staged changes with `message`.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ message = \"...\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_COMMIT_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.stash_push",
        name: "stash_push",
        since: "1.0",
        compatibility: "v1",
        doc: "Stash current dirty changes.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: false,
            doc: "{ message = \"from plugin\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_STASH_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.stash_pop",
        name: "stash_pop",
        since: "1.0",
        compatibility: "v1",
        doc: "Pop the most recent stash entry (or the entry at `index`).",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: false,
            doc: "{ index = 0 }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_STASH_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.reset",
        name: "reset",
        since: "1.0",
        compatibility: "v1",
        doc: "Reset current branch to `ref` with `mode` (soft|mixed|hard). `hard` requires destructive confirmation.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ ref = \"HEAD~1\", mode = \"soft|mixed|hard\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_RESET_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.fetch",
        name: "fetch",
        since: "1.0",
        compatibility: "v1",
        doc: "Fetch from `remote` (or every remote when omitted).",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: false,
            doc: "{ remote = \"origin\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_FETCH_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.push",
        name: "push",
        since: "1.0",
        compatibility: "v1",
        doc: "Push the current branch to `remote`. Force pushes are not yet supported.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: false,
            doc: "{ remote = \"origin\", ref = \"main\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_PUSH_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.merge",
        name: "merge",
        since: "1.0",
        compatibility: "v1",
        doc: "Merge `ref` into the current branch. Destructive — requires confirmation.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ ref = \"topic\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_MERGE_CAP,
        validation: NO_VALIDATION,
    },
    ApiFunction {
        path: "leviathan.git.rebase",
        name: "rebase",
        since: "1.0",
        compatibility: "v1",
        doc: "Rebase the current branch onto `ref`. Destructive — requires confirmation.",
        params: &[ApiParam {
            name: "opts",
            lua_type: "table",
            required: true,
            doc: "{ ref = \"main\" }",
        }],
        returns: OK_ERR_RET,
        capabilities: GIT_WRITE_REBASE_CAP,
        validation: NO_VALIDATION,
    },
];
