//! lua-language-server stub, Markdown, and schema generation.
//!
//! All generated artifacts read from `descriptor::api`, with widget
//! validation schemas coming from the same structs the runtime boundary
//! deserializes.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::descriptor::api::{self, ApiFunction, ApiModule, ApiType};
use crate::descriptor::widget::{WidgetKind, WIDGETS};

pub fn emit_stubs() -> String {
    let mut out = String::new();
    out.push_str("---@meta\n\n");
    out.push_str("-- Auto-generated by `cargo xtask gen-stubs`. Do not edit by hand.\n");
    out.push_str("-- Run `cargo xtask gen-stubs` to regenerate.\n\n");

    for ty in api::API_TYPES {
        emit_class(&mut out, ty);
    }

    for module in api::API_MODULES {
        if module.table != "leviathan" {
            writeln!(out, "{} = {} or {{}}\n", module.table, module.table).unwrap();
        } else {
            writeln!(out, "leviathan = leviathan or {{}}\n").unwrap();
        }
    }

    for function in api::all_functions() {
        emit_fn(&mut out, function);
    }

    out
}

pub fn emit_api_docs() -> BTreeMap<String, String> {
    let mut docs = BTreeMap::new();
    for module in api::API_MODULES {
        docs.insert(module_doc_filename(module), emit_module_doc(module));
    }
    docs
}

pub fn emit_api_reference() -> String {
    let mut out = String::new();
    out.push_str("# Leviathan Plugin API v1\n\n");
    out.push_str("Auto-generated by `cargo xtask gen-docs`. Do not edit by hand.\n\n");
    out.push_str("## Modules\n\n");
    for module in api::API_MODULES {
        writeln!(
            out,
            "- `{}` ({}) - {}",
            module.name, module.version.label, module.doc
        )
        .unwrap();
    }
    out.push('\n');

    out.push_str("## Events\n\n");
    for event in api::API_EVENTS {
        writeln!(
            out,
            "- `{}` ({}) - {}",
            event.name, event.payload_type, event.doc
        )
        .unwrap();
        if !event.aliases.is_empty() {
            writeln!(out, "  - aliases: `{}`", event.aliases.join("`, `")).unwrap();
        }
        if !event.payload_fields.is_empty() {
            writeln!(out, "  - payload:").unwrap();
            for field in event.payload_fields {
                let required = if field.required {
                    "required"
                } else {
                    "optional"
                };
                writeln!(
                    out,
                    "    - `{}` (`{}`; {}) - {}",
                    field.name, field.lua_type, required, field.doc
                )
                .unwrap();
            }
        }
    }
    out.push('\n');

    out.push_str("## Capabilities\n\n");
    for capability in api::API_CAPABILITIES {
        writeln!(out, "- `{}` - {}", capability.name, capability.doc).unwrap();
    }
    out.push('\n');

    out.push_str("## Widgets\n\n");
    for widget in WIDGETS.iter() {
        writeln!(out, "- `{}` - {}", widget.kind, widget.doc).unwrap();
    }
    out
}

pub fn emit_api_descriptor_json() -> String {
    let value = serde_json::to_value(api::describe()).unwrap();
    serde_json::to_string_pretty(&value).unwrap()
}

pub fn emit_widget_schema_json() -> String {
    let schema = schemars::schema_for!(WidgetKind);
    serde_json::to_string_pretty(&schema).unwrap()
}

pub fn emit_widget_descriptor_json() -> String {
    let widgets: Vec<_> = WIDGETS.iter().collect();
    serde_json::to_string_pretty(&widgets).unwrap()
}

pub fn emit_region_descriptor_json() -> String {
    let value = serde_json::to_value(api::describe().regions).unwrap();
    serde_json::to_string_pretty(&value).unwrap()
}

pub fn emit_manifest_schema_json() -> String {
    let capabilities: Vec<&str> = api::API_CAPABILITIES
        .iter()
        .map(|capability| capability.name)
        .collect();
    let schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Git Leviathan plugin.toml",
        "type": "object",
        "additionalProperties": true,
        "required": ["id", "name", "version", "api_version"],
        "properties": {
            "id": { "type": "string" },
            "name": { "type": "string" },
            "version": { "type": "string", "description": "SemVer plugin version." },
            "api_version": { "type": "string", "pattern": "^[0-9]+\\.[0-9]+$" },
            "description": { "type": "string" },
            "capabilities": {
                "type": "array",
                "items": { "type": "string", "enum": capabilities }
            },
            "provides_services": {
                "type": "array",
                "items": { "type": "string", "pattern": "^[A-Za-z0-9_.:-]+@[0-9]+$" }
            },
            "consumes_services": {
                "type": "array",
                "items": { "type": "string", "pattern": "^[A-Za-z0-9_.:-]+@[0-9]+$" }
            },
            "dependencies": {
                "type": "object",
                "additionalProperties": { "type": "string" }
            },
            "optional_dependencies": {
                "type": "object",
                "additionalProperties": { "type": "string" }
            },
            "requires_plugins": {
                "type": "array",
                "description": "Other plugin ids whose `lua/<id>/` modules this plugin may `require`.",
                "items": { "type": "string" }
            },
            "runtime": {
                "type": "object",
                "description": "Per-plugin Lua runtime configuration.",
                "additionalProperties": false,
                "properties": {
                    "strict_globals": {
                        "type": "boolean",
                        "default": true,
                        "description": "When true (default), reads/writes of undeclared Lua globals raise."
                    }
                }
            },
            "activation": {
                "type": "object",
                "description": "Phase 16 lazy-activation triggers. When omitted, the plugin loads eagerly.",
                "additionalProperties": false,
                "properties": {
                    "events": {
                        "type": "array",
                        "description": "Canonical event names. The host validates against the descriptor table.",
                        "items": { "type": "string" }
                    },
                    "commands": {
                        "type": "array",
                        "description": "Command ids the plugin will register on activation. The host installs stubs for each so palette and keymap dispatch can activate the plugin.",
                        "items": { "type": "string" }
                    },
                    "keymaps": {
                        "type": "array",
                        "description": "(context, key) pairs. The host installs lazy keymap stubs.",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": ["context", "key"],
                            "properties": {
                                "context": { "type": "string" },
                                "key": { "type": "string" }
                            }
                        }
                    },
                    "regions": {
                        "type": "array",
                        "description": "Region keys (`main_bar`, `tab_bar`, `repository`) whose first paint triggers activation.",
                        "items": { "type": "string" }
                    },
                    "files": {
                        "type": "array",
                        "description": "Relative paths in the working tree whose presence triggers activation.",
                        "items": { "type": "string" }
                    },
                    "repository_shape": {
                        "type": "object",
                        "description": "Boolean predicates over the active repository.",
                        "additionalProperties": false,
                        "properties": {
                            "has_remote": { "type": "boolean" },
                            "has_branch": { "type": "string" }
                        }
                    },
                    "manual": {
                        "type": "boolean",
                        "default": false,
                        "description": "When true, the plugin only activates on explicit user action."
                    }
                }
            }
        }
    });
    serde_json::to_string_pretty(&schema).unwrap()
}

fn emit_class(out: &mut String, ty: &ApiType) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            writeln!(out, "---{line}").unwrap();
        }
    }
    writeln!(out, "---@class {}", ty.name).unwrap();
    for field in ty.fields {
        let suffix = if field.required { "" } else { "?" };
        if field.doc.is_empty() {
            writeln!(out, "---@field {}{} {}", field.name, suffix, field.lua_type).unwrap();
        } else {
            writeln!(
                out,
                "---@field {}{} {} {}",
                field.name, suffix, field.lua_type, field.doc
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();

    for method in ty.methods {
        if !method.doc.is_empty() {
            for line in method.doc.lines() {
                writeln!(out, "---{line}").unwrap();
            }
        }
        let params_decl: Vec<&str> = method.params.iter().map(|p| p.name).collect();
        for param in method.params {
            writeln!(
                out,
                "---@param {} {} {}",
                param.name, param.lua_type, param.doc
            )
            .unwrap();
        }
        for ret in method.returns {
            writeln!(out, "---@return {} {}", ret.lua_type, ret.doc).unwrap();
        }
        writeln!(
            out,
            "function {}:{}({}) end\n",
            ty.name,
            method.name,
            params_decl.join(", ")
        )
        .unwrap();
    }
}

fn emit_fn(out: &mut String, function: &ApiFunction) {
    if !function.doc.is_empty() {
        for line in function.doc.lines() {
            writeln!(out, "---{line}").unwrap();
        }
    }
    let params_decl: Vec<&str> = function.params.iter().map(|p| p.name).collect();
    for param in function.params {
        if param.doc.is_empty() {
            writeln!(out, "---@param {} {}", param.name, param.lua_type).unwrap();
        } else {
            writeln!(
                out,
                "---@param {} {} {}",
                param.name, param.lua_type, param.doc
            )
            .unwrap();
        }
    }
    for ret in function.returns {
        if ret.doc.is_empty() {
            writeln!(out, "---@return {}", ret.lua_type).unwrap();
        } else {
            writeln!(out, "---@return {} {}", ret.lua_type, ret.doc).unwrap();
        }
    }
    writeln!(
        out,
        "function {}({}) end\n",
        function.path,
        params_decl.join(", ")
    )
    .unwrap();
}

fn emit_module_doc(module: &ApiModule) -> String {
    let mut out = String::new();
    writeln!(out, "# {}", module.table).unwrap();
    out.push('\n');
    out.push_str("Auto-generated by `cargo xtask gen-docs`. Do not edit by hand.\n\n");
    writeln!(out, "{}\n", module.doc).unwrap();
    writeln!(
        out,
        "- Version: `{}` ({})",
        module.version.label, module.version.compatibility
    )
    .unwrap();
    if !module.capabilities.is_empty() {
        writeln!(
            out,
            "- Capabilities: `{}`",
            module.capabilities.join("`, `")
        )
        .unwrap();
    }
    out.push('\n');

    let types: Vec<&ApiType> = module
        .types
        .iter()
        .filter_map(|name| api::API_TYPES.iter().find(|ty| ty.name == *name))
        .collect();
    if !types.is_empty() {
        out.push_str("## Types\n\n");
        for ty in types {
            writeln!(out, "### `{}`\n", ty.name).unwrap();
            if !ty.doc.is_empty() {
                writeln!(out, "{}\n", ty.doc).unwrap();
            }
            for field in ty.fields {
                let required = if field.required {
                    "required"
                } else {
                    "optional"
                };
                writeln!(
                    out,
                    "- `{}` (`{}`; {}) - {}",
                    field.name, field.lua_type, required, field.doc
                )
                .unwrap();
            }
            if !ty.fields.is_empty() {
                out.push('\n');
            }
            for method in ty.methods {
                let params = method
                    .params
                    .iter()
                    .map(|param| param.name)
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    out,
                    "- `{}:{}({})` - {}",
                    ty.name, method.name, params, method.doc
                )
                .unwrap();
            }
            if !ty.methods.is_empty() {
                out.push('\n');
            }
        }
    }

    if !module.events.is_empty() {
        out.push_str("## Events\n\n");
        for event_name in module.events {
            if let Some(event) = api::API_EVENTS.iter().find(|e| &e.name == event_name) {
                writeln!(
                    out,
                    "- `{}` ({}) - {}",
                    event.name, event.payload_type, event.doc
                )
                .unwrap();
                if !event.aliases.is_empty() {
                    writeln!(out, "  - aliases: `{}`", event.aliases.join("`, `")).unwrap();
                }
                for field in event.payload_fields {
                    let required = if field.required {
                        "required"
                    } else {
                        "optional"
                    };
                    writeln!(
                        out,
                        "  - `{}` (`{}`; {}) - {}",
                        field.name, field.lua_type, required, field.doc
                    )
                    .unwrap();
                }
            } else {
                writeln!(out, "- `{}`", event_name).unwrap();
            }
        }
        out.push('\n');
    }

    out.push_str("## Functions\n\n");
    if module.functions.is_empty() {
        out.push_str("_No functions._\n\n");
    }
    for function in module.functions {
        let params = function
            .params
            .iter()
            .map(|param| param.name)
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "### `{}({})`\n", function.path, params).unwrap();
        if !function.doc.is_empty() {
            writeln!(out, "{}\n", function.doc).unwrap();
        }
        if !function.capabilities.is_empty() {
            writeln!(
                out,
                "**Capabilities:** `{}`\n",
                function.capabilities.join("`, `")
            )
            .unwrap();
        }
        if !function.params.is_empty() {
            out.push_str("**Parameters:**\n");
            for param in function.params {
                let required = if param.required {
                    "required"
                } else {
                    "optional"
                };
                writeln!(
                    out,
                    "- `{}` (`{}`; {}) - {}",
                    param.name, param.lua_type, required, param.doc
                )
                .unwrap();
            }
            out.push('\n');
        }
        if !function.returns.is_empty() {
            out.push_str("**Returns:**\n");
            for ret in function.returns {
                writeln!(out, "- `{}` - {}", ret.lua_type, ret.doc).unwrap();
            }
            out.push('\n');
        }
    }

    out
}

fn module_doc_filename(module: &ApiModule) -> String {
    if module.name == "root" {
        "root.md".to_string()
    } else {
        format!("{}.md", module.name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stub_for_fs_read_file_present() {
        let s = emit_stubs();
        assert!(s.contains("---@class leviathan.fs"));
        assert!(s.contains("function leviathan.fs.read_file(path) end"));
        assert!(s.contains("---@param path string"));
    }

    #[test]
    fn stub_includes_all_regions() {
        let s = emit_stubs();
        for region in ["main_bar", "tab_bar", "repository"] {
            let needle = format!("function leviathan.ui.{region}.add(spec) end");
            assert!(s.contains(&needle), "missing {needle}");
        }
    }

    #[test]
    fn stub_documents_repository_class() {
        let s = emit_stubs();
        assert!(s.contains("---@class leviathan.repository"));
        assert!(s.contains("---@field name string"));
        assert!(s.contains("---@field current_branch_name string"));
    }

    #[test]
    fn generated_schema_includes_widget_kind() {
        let s = emit_widget_schema_json();
        assert!(s.contains("text"));
        assert!(s.contains("resizable_split"));
    }

    #[test]
    fn generated_docs_include_describe_and_health() {
        let docs = emit_api_docs();
        assert!(docs["api.md"].contains("leviathan.api.describe"));
        assert!(docs["health.md"].contains("leviathan.health.register"));
    }
}
