//! lua-language-server stub, Markdown, and schema generation.
//!
//! All generated artifacts read from `descriptor::api`, with widget
//! validation schemas coming from the same structs the runtime boundary
//! deserializes.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::descriptor::api::{self, ApiFunction, ApiModule, ApiType};
use crate::descriptor::extension_point::EXTENSION_POINTS;
use crate::descriptor::widget::{WidgetKind, WIDGETS};

pub fn emit_stubs() -> String {
    let mut out = String::new();
    out.push_str("---@meta\n\n");
    out.push_str("-- Auto-generated by `cargo xtask gen-stubs`. Do not edit by hand.\n");
    out.push_str("-- Run `cargo xtask gen-stubs` to regenerate.\n\n");

    for ty in api::API_TYPES {
        if ty.name == "LeviathanWidget" {
            continue;
        }
        emit_class(&mut out, ty);
    }
    emit_widget_classes(&mut out);

    for module in api::API_MODULES {
        if module.table != "leviathan" {
            writeln!(out, "{} = {} or {{}}\n", module.table, module.table).unwrap();
        } else {
            writeln!(out, "leviathan = leviathan or {{}}\n").unwrap();
        }
    }

    for function in api::all_functions() {
        emit_fn(&mut out, function);
    }

    trim_trailing_blank_lines(out)
}

pub fn emit_api_docs() -> BTreeMap<String, String> {
    let mut docs = BTreeMap::new();
    for module in api::API_MODULES {
        docs.insert(module_doc_filename(module), emit_module_doc(module));
    }
    docs
}

pub fn emit_api_reference() -> String {
    let mut out = String::new();
    out.push_str("# Leviathan Plugin API v1\n\n");
    out.push_str("Auto-generated by `cargo xtask gen-docs`. Do not edit by hand.\n\n");
    emit_stability_summary(&mut out);
    out.push_str("## Modules\n\n");
    for module in api::API_MODULES {
        writeln!(
            out,
            "- `{}` ({}) - {}",
            module.name, module.version.label, module.doc
        )
        .unwrap();
    }
    out.push('\n');

    out.push_str("## Events\n\n");
    for event in api::API_EVENTS {
        writeln!(
            out,
            "- `{}` ({}) - {}",
            event.name, event.payload_type, event.doc
        )
        .unwrap();
        if !event.aliases.is_empty() {
            writeln!(out, "  - aliases: `{}`", event.aliases.join("`, `")).unwrap();
        }
        if !event.payload_fields.is_empty() {
            writeln!(out, "  - payload:").unwrap();
            for field in event.payload_fields {
                let required = if field.required {
                    "required"
                } else {
                    "optional"
                };
                writeln!(
                    out,
                    "    - `{}` (`{}`; {}) - {}",
                    field.name, field.lua_type, required, field.doc
                )
                .unwrap();
            }
        }
    }
    out.push('\n');

    out.push_str("## Capabilities\n\n");
    for capability in api::API_CAPABILITIES {
        writeln!(out, "- `{}` - {}", capability.name, capability.doc).unwrap();
    }
    out.push('\n');

    out.push_str("## Widgets\n\n");
    for widget in WIDGETS.iter() {
        writeln!(
            out,
            "- `{}` (since {}; stable) - {}",
            widget.kind, widget.since, widget.doc
        )
        .unwrap();
    }
    out
}

pub fn emit_api_descriptor_json() -> String {
    let value = serde_json::to_value(api::describe()).unwrap();
    serde_json::to_string_pretty(&value).unwrap()
}

pub fn emit_widget_schema_json() -> String {
    let schema = schemars::schema_for!(WidgetKind);
    serde_json::to_string_pretty(&schema).unwrap()
}

pub fn emit_widget_descriptor_json() -> String {
    let widgets: Vec<_> = WIDGETS.iter().collect();
    serde_json::to_string_pretty(&widgets).unwrap()
}

pub fn emit_region_descriptor_json() -> String {
    let value = serde_json::to_value(api::describe().regions).unwrap();
    serde_json::to_string_pretty(&value).unwrap()
}

pub fn emit_devtools_extension_point_summary_json() -> String {
    let extension_points: Vec<_> = EXTENSION_POINTS.iter().collect();
    let value = serde_json::json!({
        "schema_version": 1,
        "title": "Git Leviathan plugin UI devtools extension-point summary",
        "sources": [
            "src/plugin/devtools.rs::InspectorSnapshot",
            "src/plugin/host/core/runtime_introspection.rs::PluginHost::introspect",
            "src/plugin/extensions.rs::ExtensionRegistry"
        ],
        "extension_points": extension_points,
        "collections": [
            {
                "name": "slots",
                "snapshot_field": "InspectorSnapshot.slots",
                "owner_field": "owner_plugin_id",
                "identity": ["region", "container", "id"],
                "ordering": "host replay order; per-render registries sort by priority ascending with insertion-order ties",
                "fields": [
                    { "name": "region", "type": "string" },
                    { "name": "container", "type": "string" },
                    { "name": "id", "type": "string" },
                    { "name": "priority", "type": "integer" },
                    { "name": "owner_plugin_id", "type": "string" }
                ],
                "dynamic_context": "dynamic widget functions receive the typed context for their mounted surface"
            },
            {
                "name": "ui_contexts",
                "snapshot_field": "Plugin: Inspect UI Context",
                "identity": ["type", "surface"],
                "mounted_context_types": [
                    "MainBarContext",
                    "TabBarContext",
                    "RepositorySidebarContext",
                    "RepositoryGraphContext",
                    "RepositoryDetailsContext"
                ],
                "placeholder_context_types": [
                    "StatusBarContext",
                    "RepositoryDiffContext",
                    "RepositoryGraphRowContext",
                    "RepositoryDiffLineContext",
                    "OverlayContext",
                    "ScreenContext",
                    "SettingsContext"
                ],
                "fields": [
                    { "name": "version", "type": "integer" },
                    { "name": "type", "type": "string" },
                    { "name": "surface", "type": "string" },
                    { "name": "features", "type": "table<string, boolean>" },
                    { "name": "theme", "type": "LeviathanUiThemeTokens" },
                    { "name": "repository", "type": "LeviathanRepositorySummary" },
                    { "name": "tab", "type": "LeviathanTabSummary" },
                    { "name": "selection", "type": "LeviathanSelectionSummary" },
                    { "name": "focus", "type": "LeviathanFocusSummary" },
                    { "name": "viewport", "type": "LeviathanViewportSummary" },
                    { "name": "payload", "type": "table" }
                ]
            },
            {
                "name": "overlays",
                "snapshot_field": "InspectorSnapshot.overlays",
                "api": "leviathan.ui.overlay",
                "remove_api": "leviathan.ui.remove_overlay",
                "capability": "ui:overlay",
                "identity": ["plugin_id", "id"],
                "ordering": "priority descending, then plugin_id, then id",
                "fields": [
                    { "name": "plugin_id", "type": "string" },
                    { "name": "id", "type": "string" },
                    { "name": "priority", "type": "integer" },
                    { "name": "dismissible", "type": "boolean" },
                    { "name": "key_events", "type": "string[]" },
                    { "name": "widget", "type": "LeviathanWidget" },
                    { "name": "source_location", "type": "string|null" }
                ]
            },
            {
                "name": "context_menu_items",
                "snapshot_field": "InspectorSnapshot.context_menu_items",
                "api": "leviathan.ui.context_menu",
                "capability": "ui:context_menu:<region>",
                "identity": ["plugin_id", "region", "id"],
                "ordering": "region, priority ascending, plugin_id, id",
                "fields": [
                    { "name": "plugin_id", "type": "string" },
                    { "name": "region", "type": "string" },
                    { "name": "id", "type": "string" },
                    { "name": "label", "type": "string" },
                    { "name": "command", "type": "string" },
                    { "name": "priority", "type": "integer" },
                    { "name": "condition_capability", "type": "string|null" },
                    { "name": "source_location", "type": "string|null" }
                ]
            },
            {
                "name": "dock_panels",
                "snapshot_field": "InspectorSnapshot.dock_panels",
                "api": "leviathan.ui.dock.register",
                "capability": "ui:dock",
                "identity": ["plugin_id", "id"],
                "ordering": "area order, then panel order, plugin_id, id",
                "fields": [
                    { "name": "plugin_id", "type": "string" },
                    { "name": "generation_id", "type": "integer" },
                    { "name": "id", "type": "string" },
                    { "name": "key", "type": "string" },
                    { "name": "title", "type": "string" },
                    { "name": "area", "type": "string" },
                    { "name": "open", "type": "boolean" },
                    { "name": "selected", "type": "boolean" },
                    { "name": "state", "type": "LeviathanJson" }
                ],
                "dynamic_context": "view callbacks receive DockPanelContext with payload.dock metadata and persisted state"
            },
            {
                "name": "graph_decorations",
                "snapshot_field": "InspectorSnapshot.graph_decorations",
                "api": "leviathan.ui.graph_decoration",
                "capability": "ui:decoration:graph",
                "identity": ["plugin_id", "commit_hash", "id"],
                "ordering": "commit_hash, plugin_id, id",
                "fields": [
                    { "name": "plugin_id", "type": "string" },
                    { "name": "id", "type": "string" },
                    { "name": "commit_hash", "type": "string" },
                    { "name": "kind", "type": "badge|icon|marker|lane" },
                    { "name": "decoration", "type": "LeviathanGraphDecoration" },
                    { "name": "source_location", "type": "string|null" }
                ]
            },
            {
                "name": "diff_decorations",
                "snapshot_field": "InspectorSnapshot.diff_decorations",
                "api": "leviathan.ui.diff_decoration",
                "capability": "ui:decoration:diff",
                "identity": ["plugin_id", "id"],
                "ordering": "plugin_id, id",
                "fields": [
                    { "name": "plugin_id", "type": "string" },
                    { "name": "id", "type": "string" },
                    { "name": "kind", "type": "line_hint|hunk_badge|line_gutter" },
                    { "name": "decoration", "type": "LeviathanDiffDecoration" },
                    { "name": "source_location", "type": "string|null" }
                ]
            }
        ],
        "cleanup": {
            "unload": "PluginHost::unload_plugin drops slot ops, dock panels, overlays, context menu items, graph decorations, and diff decorations owned by the plugin.",
            "reload": "successful reload clears previous generation extension records before staged records are installed; failed reload keeps the previous generation live"
        }
    });
    serde_json::to_string_pretty(&value).unwrap()
}

pub fn emit_manifest_schema_json() -> String {
    let capabilities: Vec<&str> = api::API_CAPABILITIES
        .iter()
        .map(|capability| capability.name)
        .collect();
    let schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Git Leviathan plugin.toml",
        "type": "object",
        "additionalProperties": true,
        "required": ["id", "name", "version", "api_version"],
        "properties": {
            "id": { "type": "string" },
            "name": { "type": "string" },
            "version": { "type": "string", "description": "SemVer plugin version." },
            "api_version": {
                "type": "string",
                "enum": ["1.0"],
                "description": "Stable plugin API version supported by this host."
            },
            "debug": {
                "type": "boolean",
                "default": false,
                "description": "When true, forward this plugin's diagnostics and leviathan.log messages to stdout. Diagnostics are retained in devtools either way."
            },
            "description": { "type": "string" },
            "capabilities": {
                "type": "array",
                "items": { "type": "string", "enum": capabilities }
            },
            "provides_services": {
                "type": "array",
                "items": { "type": "string", "pattern": "^[A-Za-z0-9_.:-]+@[0-9]+$" }
            },
            "consumes_services": {
                "type": "array",
                "items": { "type": "string", "pattern": "^[A-Za-z0-9_.:-]+@[0-9]+$" }
            },
            "dependencies": {
                "type": "object",
                "additionalProperties": { "type": "string" }
            },
            "optional_dependencies": {
                "type": "object",
                "additionalProperties": { "type": "string" }
            },
            "requires_plugins": {
                "type": "array",
                "description": "Other plugin ids whose `lua/<id>/` modules this plugin may `require`.",
                "items": { "type": "string" }
            },
            "runtime": {
                "type": "object",
                "description": "Per-plugin Lua runtime configuration.",
                "additionalProperties": false,
                "properties": {
                    "strict_globals": {
                        "type": "boolean",
                        "default": true,
                        "description": "When true (default), reads/writes of undeclared Lua globals raise."
                    }
                }
            },
            "activation": {
                "type": "object",
                "description": "lazy activation triggers. When omitted, the plugin loads eagerly.",
                "additionalProperties": false,
                "properties": {
                    "events": {
                        "type": "array",
                        "description": "Canonical event names. The host validates against the descriptor table.",
                        "items": { "type": "string" }
                    },
                    "commands": {
                        "type": "array",
                        "description": "Command ids the plugin will register on activation. The host installs stubs for each so palette and keymap dispatch can activate the plugin.",
                        "items": { "type": "string" }
                    },
                    "keymaps": {
                        "type": "array",
                        "description": "(context, key) pairs. The host installs lazy keymap stubs.",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": ["context", "key"],
                            "properties": {
                                "context": { "type": "string" },
                                "key": { "type": "string" }
                            }
                        }
                    },
                    "regions": {
                        "type": "array",
                        "description": "Region keys (`main_bar`, `tab_bar`, `repository`) whose first paint triggers activation.",
                        "items": { "type": "string" }
                    },
                    "files": {
                        "type": "array",
                        "description": "Relative paths in the working tree whose presence triggers activation.",
                        "items": { "type": "string" }
                    },
                    "repository_shape": {
                        "type": "object",
                        "description": "Boolean predicates over the active repository.",
                        "additionalProperties": false,
                        "properties": {
                            "has_remote": { "type": "boolean" },
                            "has_branch": { "type": "string" }
                        }
                    },
                    "manual": {
                        "type": "boolean",
                        "default": false,
                        "description": "When true, the plugin only activates on explicit user action."
                    }
                }
            }
        }
    });
    serde_json::to_string_pretty(&schema).unwrap()
}

fn emit_class(out: &mut String, ty: &ApiType) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            writeln!(out, "---{line}").unwrap();
        }
    }
    writeln!(out, "---@class {}", ty.name).unwrap();
    for field in ty.fields {
        let suffix = if field.required { "" } else { "?" };
        if field.doc.is_empty() {
            writeln!(out, "---@field {}{} {}", field.name, suffix, field.lua_type).unwrap();
        } else {
            writeln!(
                out,
                "---@field {}{} {} {}",
                field.name, suffix, field.lua_type, field.doc
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();

    for method in ty.methods {
        if !method.doc.is_empty() {
            for line in method.doc.lines() {
                writeln!(out, "---{line}").unwrap();
            }
        }
        let params_decl: Vec<&str> = method.params.iter().map(|p| p.name).collect();
        for param in method.params {
            writeln!(
                out,
                "---@param {} {} {}",
                param.name, param.lua_type, param.doc
            )
            .unwrap();
        }
        for ret in method.returns {
            writeln!(out, "---@return {} {}", ret.lua_type, ret.doc).unwrap();
        }
        writeln!(
            out,
            "function {}:{}({}) end\n",
            ty.name,
            method.name,
            params_decl.join(", ")
        )
        .unwrap();
    }
}

fn emit_widget_classes(out: &mut String) {
    let widget_types: Vec<String> = WIDGETS.iter().map(widget_type_name).collect();
    writeln!(out, "---Tagged widget tree node.").unwrap();
    writeln!(out, "---@alias LeviathanWidget {}", widget_types.join("|")).unwrap();
    writeln!(out).unwrap();

    for widget in WIDGETS.iter() {
        let type_name = widget_type_name(widget);
        if !widget.doc.is_empty() {
            for line in widget.doc.lines() {
                writeln!(out, "---{line}").unwrap();
            }
        }
        writeln!(out, "---@class {type_name}").unwrap();
        writeln!(out, "---@field kind \"{}\"", widget.kind).unwrap();
        for field in widget.fields {
            let suffix = if field.required { "" } else { "?" };
            if field.doc.is_empty() {
                writeln!(out, "---@field {}{} {}", field.name, suffix, field.lua_type).unwrap();
            } else {
                writeln!(
                    out,
                    "---@field {}{} {} {}",
                    field.name, suffix, field.lua_type, field.doc
                )
                .unwrap();
            }
        }
        writeln!(out).unwrap();
    }
}

fn widget_type_name(widget: &crate::descriptor::widget::WidgetDescriptor) -> String {
    let mut out = String::from("Leviathan");
    for part in widget.kind.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.extend(chars);
        }
    }
    out.push_str("Widget");
    out
}

fn emit_fn(out: &mut String, function: &ApiFunction) {
    if !function.doc.is_empty() {
        for line in function.doc.lines() {
            writeln!(out, "---{line}").unwrap();
        }
    }
    let params_decl: Vec<&str> = function.params.iter().map(|p| p.name).collect();
    for param in function.params {
        if param.doc.is_empty() {
            writeln!(out, "---@param {} {}", param.name, param.lua_type).unwrap();
        } else {
            writeln!(
                out,
                "---@param {} {} {}",
                param.name, param.lua_type, param.doc
            )
            .unwrap();
        }
    }
    for ret in function.returns {
        if ret.doc.is_empty() {
            writeln!(out, "---@return {}", ret.lua_type).unwrap();
        } else {
            writeln!(out, "---@return {} {}", ret.lua_type, ret.doc).unwrap();
        }
    }
    writeln!(
        out,
        "function {}({}) end\n",
        function.path,
        params_decl.join(", ")
    )
    .unwrap();
}

fn emit_stability_summary(out: &mut String) {
    let desc = api::describe();
    let policy = desc.stability_policy;
    writeln!(out, "## Stability\n").unwrap();
    writeln!(
        out,
        "- Public API: `{}` ({})",
        policy.public_api_version, policy.stability
    )
    .unwrap();
    writeln!(out, "- Descriptor version: `{}`", policy.descriptor_version).unwrap();
    writeln!(out, "- Widget schema: `{}`", policy.widget_schema_version).unwrap();
    writeln!(
        out,
        "- Extension-point schema: `{}`",
        policy.extension_point_schema_version
    )
    .unwrap();
    writeln!(out, "- Migration promise: {}\n", policy.migration_promise).unwrap();

    out.push_str("## Compatibility Matrix\n\n");
    out.push_str("| Host | Plugin API | Widget schema | Extension points |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for row in desc.compatibility_matrix {
        writeln!(
            out,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.host_version,
            row.plugin_api_version,
            row.widget_schema,
            row.extension_points.join("`, `")
        )
        .unwrap();
    }
    out.push('\n');

    let semver = desc.semver_policy;
    out.push_str("## Semver Policy\n\n");
    writeln!(
        out,
        "- Descriptor versioning: {}",
        semver.descriptor_versioning
    )
    .unwrap();
    writeln!(out, "- Additions: {}", semver.can_add.join("; ")).unwrap();
    writeln!(
        out,
        "- Deprecation required: {}",
        semver.requires_deprecation.join("; ")
    )
    .unwrap();
    writeln!(out, "- Removals: {}\n", semver.can_remove.join("; ")).unwrap();

    out.push_str("## Experimental APIs\n\n");
    if desc.experimental_apis.is_empty() {
        out.push_str("No experimental APIs are exposed in plugin API 1.0.\n\n");
    } else {
        for item in desc.experimental_apis {
            writeln!(
                out,
                "- `{}` since `{}`: {}; {}",
                item.path, item.since, item.stability, item.migration_promise
            )
            .unwrap();
        }
        out.push('\n');
    }
}

fn emit_module_doc(module: &ApiModule) -> String {
    let mut out = String::new();
    writeln!(out, "# {}", module.table).unwrap();
    out.push('\n');
    out.push_str("Auto-generated by `cargo xtask gen-docs`. Do not edit by hand.\n\n");
    writeln!(out, "{}\n", module.doc).unwrap();
    writeln!(
        out,
        "- Version: `{}` ({})",
        module.version.label, module.version.compatibility
    )
    .unwrap();
    writeln!(out, "- Stability: `stable`").unwrap();
    writeln!(
        out,
        "- Migration promise: source-compatible additions only within host 1.x"
    )
    .unwrap();
    if !module.capabilities.is_empty() {
        writeln!(
            out,
            "- Capabilities: `{}`",
            module.capabilities.join("`, `")
        )
        .unwrap();
    }
    out.push('\n');

    let types: Vec<&ApiType> = module
        .types
        .iter()
        .filter_map(|name| api::API_TYPES.iter().find(|ty| ty.name == *name))
        .collect();
    if !types.is_empty() {
        out.push_str("## Types\n\n");
        for ty in types {
            writeln!(out, "### `{}`\n", ty.name).unwrap();
            if !ty.doc.is_empty() {
                writeln!(out, "{}\n", ty.doc).unwrap();
            }
            for field in ty.fields {
                let required = if field.required {
                    "required"
                } else {
                    "optional"
                };
                writeln!(
                    out,
                    "- `{}` (`{}`; {}) - {}",
                    field.name, field.lua_type, required, field.doc
                )
                .unwrap();
            }
            if !ty.fields.is_empty() {
                out.push('\n');
            }
            for method in ty.methods {
                let params = method
                    .params
                    .iter()
                    .map(|param| param.name)
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    out,
                    "- `{}:{}({})` - {}",
                    ty.name, method.name, params, method.doc
                )
                .unwrap();
            }
            if !ty.methods.is_empty() {
                out.push('\n');
            }
        }
    }

    if !module.events.is_empty() {
        out.push_str("## Events\n\n");
        for event_name in module.events {
            if let Some(event) = api::API_EVENTS.iter().find(|e| &e.name == event_name) {
                writeln!(
                    out,
                    "- `{}` ({}) - {}",
                    event.name, event.payload_type, event.doc
                )
                .unwrap();
                if !event.aliases.is_empty() {
                    writeln!(out, "  - aliases: `{}`", event.aliases.join("`, `")).unwrap();
                }
                for field in event.payload_fields {
                    let required = if field.required {
                        "required"
                    } else {
                        "optional"
                    };
                    writeln!(
                        out,
                        "  - `{}` (`{}`; {}) - {}",
                        field.name, field.lua_type, required, field.doc
                    )
                    .unwrap();
                }
            } else {
                writeln!(out, "- `{}`", event_name).unwrap();
            }
        }
        out.push('\n');
    }

    out.push_str("## Functions\n\n");
    if module.functions.is_empty() {
        out.push_str("_No functions._\n\n");
    }
    for function in module.functions {
        let params = function
            .params
            .iter()
            .map(|param| param.name)
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "### `{}({})`\n", function.path, params).unwrap();
        if !function.doc.is_empty() {
            writeln!(out, "{}\n", function.doc).unwrap();
        }
        if !function.capabilities.is_empty() {
            writeln!(
                out,
                "**Capabilities:** `{}`\n",
                function.capabilities.join("`, `")
            )
            .unwrap();
        }
        writeln!(out, "**Since:** `{}`", function.since).unwrap();
        writeln!(
            out,
            "**Stability:** `stable` ({})\n",
            function.compatibility
        )
        .unwrap();
        if !function.params.is_empty() {
            out.push_str("**Parameters:**\n");
            for param in function.params {
                let required = if param.required {
                    "required"
                } else {
                    "optional"
                };
                writeln!(
                    out,
                    "- `{}` (`{}`; {}) - {}",
                    param.name, param.lua_type, required, param.doc
                )
                .unwrap();
            }
            out.push('\n');
        }
        if !function.returns.is_empty() {
            out.push_str("**Returns:**\n");
            for ret in function.returns {
                writeln!(out, "- `{}` - {}", ret.lua_type, ret.doc).unwrap();
            }
            out.push('\n');
        }
    }

    trim_trailing_blank_lines(out)
}

fn module_doc_filename(module: &ApiModule) -> String {
    if module.name == "root" {
        "root.md".to_string()
    } else {
        format!("{}.md", module.name)
    }
}

fn trim_trailing_blank_lines(mut out: String) -> String {
    while out.ends_with("\n\n") {
        out.pop();
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn removed_ui_terms() -> Vec<String> {
        vec![
            ["leviathan.ui.", "regions"].concat(),
            ["leviathan.ui.", "main_bar"].concat(),
            ["ui", ".", "v", "2"].concat(),
            ["ui", "_", "v", "2"].concat(),
            ["regions", ".add_slot"].concat(),
            ["regions", ".replace_slot"].concat(),
            ["regions", ".remove_slot"].concat(),
            ["compatibility", " alias"].concat(),
            ["compatibility", " grant"].concat(),
            ["migration", " guide"].concat(),
        ]
    }

    #[test]
    fn stub_for_fs_read_file_present() {
        let s = emit_stubs();
        assert!(s.contains("---@class leviathan.fs"));
        assert!(s.contains("function leviathan.fs.read_file(path) end"));
        assert!(s.contains("---@param path string"));
    }

    #[test]
    fn stub_includes_region_slot_api() {
        let s = emit_stubs();
        for needle in [
            "function leviathan.ui.slot.add(spec) end",
            "function leviathan.ui.slot.remove(target) end",
            "function leviathan.ui.slot.replace(target, spec) end",
            "function leviathan.ui.region.list() end",
            "function leviathan.ui.region.describe(name) end",
            "function leviathan.ui.context.current() end",
            "---@class leviathan.ui.screen",
            "function leviathan.ui.dock.register(spec) end",
            "---@class LeviathanDockPanelSpec",
            "---@class LeviathanDockPanelHandle",
            "---@class DockPanelContext",
        ] {
            assert!(s.contains(needle), "missing {needle}");
        }
    }

    #[test]
    fn region_descriptor_includes_all_regions() {
        let s = emit_region_descriptor_json();
        for region in ["main_bar", "tab_bar", "repository"] {
            let needle = format!("\"name\": \"{region}\"");
            assert!(s.contains(&needle), "missing {needle}");
        }
    }

    #[test]
    fn stub_documents_repository_class() {
        let s = emit_stubs();
        assert!(s.contains("---@class leviathan.repository"));
        assert!(s.contains("---@field name string"));
        assert!(s.contains("---@field current_branch_name string"));
    }

    #[test]
    fn generated_schema_includes_widget_kind() {
        let s = emit_widget_schema_json();
        assert!(s.contains("text"));
        assert!(s.contains("resizable_split"));
    }

    #[test]
    fn generated_docs_include_describe_and_health() {
        let docs = emit_api_docs();
        assert!(docs["api.md"].contains("leviathan.api.describe"));
        assert!(docs["health.md"].contains("leviathan.health.register"));
    }

    #[test]
    fn generated_reference_includes_stable_contract() {
        let docs = emit_api_reference();
        assert!(docs.contains("## Compatibility Matrix"));
        assert!(docs.contains("| `1.0` | `1.0` | `1` |"));
        assert!(docs.contains("## Semver Policy"));
        assert!(docs.contains("No experimental APIs are exposed in plugin API 1.0."));
    }

    #[test]
    fn generated_stubs_do_not_document_retired_ui_names() {
        assert_absent("stubs", &emit_stubs());
    }

    #[test]
    fn generated_docs_do_not_document_retired_ui_names() {
        assert_absent("api reference", &emit_api_reference());
        for (filename, content) in emit_api_docs() {
            assert_absent(&filename, &content);
        }
    }

    fn assert_absent(label: &str, content: &str) {
        let lower = content.to_ascii_lowercase();
        for term in removed_ui_terms() {
            assert!(
                !lower.contains(&term),
                "{label} contains retired UI term `{term}`"
            );
        }
    }
}
