//! lua-language-server stub generator.
//!
//! Builds annotation text describing the public `leviathan.*` API
//! surface so plugin authors get autocomplete and hover docs in any
//! editor backed by lua-language-server. Driven by hand-curated
//! function metadata; the descriptor table contributes per-region
//! handles automatically.
//!
//! Output is deterministic so CI can `git diff --exit-code` against a
//! committed copy.

use std::fmt::Write;

use crate::descriptor::region::REGIONS;

#[derive(Debug, Clone)]
pub struct ParamDoc {
    pub name: &'static str,
    pub ty: &'static str,
    pub doc: &'static str,
}

#[derive(Debug, Clone)]
pub struct FnDoc {
    pub path: &'static str,
    pub params: &'static [ParamDoc],
    pub returns: &'static str,
    pub doc: &'static str,
}

#[derive(Debug, Clone)]
pub struct ClassDoc {
    pub name: &'static str,
    pub fields: &'static [(&'static str, &'static str, &'static str)],
    pub doc: &'static str,
}

pub fn emit_stubs() -> String {
    let mut out = String::new();
    out.push_str("---@meta\n\n");
    out.push_str("-- Auto-generated by `cargo xtask gen-stubs`. Do not edit by hand.\n");
    out.push_str("-- Run `cargo xtask gen-stubs` to regenerate.\n\n");

    writeln!(out, "---@class leviathan").unwrap();
    writeln!(out, "leviathan = {{}}\n").unwrap();

    for cls in CLASSES {
        if !cls.doc.is_empty() {
            for line in cls.doc.lines() {
                writeln!(out, "---{line}").unwrap();
            }
        }
        writeln!(out, "---@class {}", cls.name).unwrap();
        for (fname, fty, fdoc) in cls.fields {
            if !fdoc.is_empty() {
                writeln!(out, "---@field {fname} {fty} {fdoc}").unwrap();
            } else {
                writeln!(out, "---@field {fname} {fty}").unwrap();
            }
        }
        writeln!(out, "{} = {{}}\n", cls.name).unwrap();
    }

    for f in FUNCTIONS {
        emit_fn(&mut out, f);
    }

    for region in REGIONS.iter() {
        let ns = format!("leviathan.ui.{}", region.name);
        writeln!(out, "---@class {ns}").unwrap();
        writeln!(out, "{ns} = {{}}\n").unwrap();
        emit_region_fn(
            &mut out,
            &ns,
            "add",
            "Add a slot to this region.",
            "spec",
            "table",
        );
        emit_region_fn(
            &mut out,
            &ns,
            "remove",
            "Remove a slot from this region.",
            "target",
            "table",
        );
        emit_region_fn(
            &mut out,
            &ns,
            "replace",
            "Replace a slot. First arg targets the existing slot.",
            "target_and_spec",
            "table, table",
        );
    }

    out
}

fn emit_fn(out: &mut String, f: &FnDoc) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            writeln!(out, "---{line}").unwrap();
        }
    }
    let params_decl: Vec<String> = f.params.iter().map(|p| p.name.to_string()).collect();
    for p in f.params {
        if p.doc.is_empty() {
            writeln!(out, "---@param {} {}", p.name, p.ty).unwrap();
        } else {
            writeln!(out, "---@param {} {} {}", p.name, p.ty, p.doc).unwrap();
        }
    }
    if !f.returns.is_empty() {
        writeln!(out, "---@return {}", f.returns).unwrap();
    }
    writeln!(out, "function {}({}) end\n", f.path, params_decl.join(", ")).unwrap();
}

fn emit_region_fn(
    out: &mut String,
    ns: &str,
    verb: &str,
    doc: &str,
    param_name: &str,
    param_ty: &str,
) {
    writeln!(out, "---{doc}").unwrap();
    writeln!(out, "---@param {param_name} {param_ty}").unwrap();
    writeln!(out, "function {ns}.{verb}({param_name}) end\n").unwrap();
}

const CLASSES: &[ClassDoc] = &[
    ClassDoc { name: "leviathan.fs", fields: &[], doc: "" },
    ClassDoc { name: "leviathan.env", fields: &[], doc: "" },
    ClassDoc { name: "leviathan.api", fields: &[], doc: "" },
    ClassDoc { name: "leviathan.ui", fields: &[], doc: "" },
    ClassDoc {
        name: "leviathan.tab_registry",
        fields: &[
            ("list", "table[]", "Array of open tab descriptors."),
            ("current", "table?", "The currently focused tab or nil."),
        ],
        doc: "",
    },
    ClassDoc {
        name: "leviathan.repository",
        fields: &[
            ("name", "string", ""),
            ("workdir_path", "string", ""),
            ("current_branch_name", "string", ""),
            ("current_branch", "table?", ""),
            ("is_open", "boolean", ""),
            ("is_detached", "boolean", ""),
            ("is_unborn", "boolean", ""),
            ("is_bare", "boolean", ""),
            ("head_hash", "string?", ""),
            ("default_remote_name", "string?", ""),
            ("local_branches", "table[]", ""),
            ("remote_branches", "table[]", ""),
            ("tags", "table[]", ""),
        ],
        doc: "Live snapshot of the active repository.",
    },
];

const FUNCTIONS: &[FnDoc] = &[
    FnDoc {
        path: "leviathan.log",
        params: &[ParamDoc { name: "message", ty: "string", doc: "Message to log to host stderr." }],
        returns: "",
        doc: "Log a message via the host.",
    },

    FnDoc { path: "leviathan.fs.read_file", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string|nil, string|nil", doc: "Read file contents. Returns content or (nil, err)." },
    FnDoc { path: "leviathan.fs.read_lines", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string[]|nil, string|nil", doc: "Read file as array of lines." },
    FnDoc { path: "leviathan.fs.write_file", params: &[ParamDoc { name: "path", ty: "string", doc: "" }, ParamDoc { name: "content", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Write content to file. Returns (ok, err)." },
    FnDoc { path: "leviathan.fs.append_file", params: &[ParamDoc { name: "path", ty: "string", doc: "" }, ParamDoc { name: "content", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Append content to file." },
    FnDoc { path: "leviathan.fs.delete", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Delete a file or directory." },
    FnDoc { path: "leviathan.fs.mkdir", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Create a directory (recursive)." },
    FnDoc { path: "leviathan.fs.copy", params: &[ParamDoc { name: "src", ty: "string", doc: "" }, ParamDoc { name: "dst", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Copy file from src to dst." },
    FnDoc { path: "leviathan.fs.rename", params: &[ParamDoc { name: "src", ty: "string", doc: "" }, ParamDoc { name: "dst", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Rename / move file." },
    FnDoc { path: "leviathan.fs.touch", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean, string|nil", doc: "Create empty file at path." },
    FnDoc { path: "leviathan.fs.read_link", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string|nil, string|nil", doc: "Read symlink target." },
    FnDoc { path: "leviathan.fs.list_dir", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "table[]|nil, string|nil", doc: "List directory entries." },
    FnDoc { path: "leviathan.fs.exists", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean", doc: "" },
    FnDoc { path: "leviathan.fs.is_file", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean", doc: "" },
    FnDoc { path: "leviathan.fs.is_dir", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean", doc: "" },
    FnDoc { path: "leviathan.fs.is_symlink", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean", doc: "" },
    FnDoc { path: "leviathan.fs.size", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "integer|nil, string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.modified", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "number|nil, string|nil", doc: "Modification time as unix epoch." },
    FnDoc { path: "leviathan.fs.metadata", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "table|nil, string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.is_absolute", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "boolean", doc: "" },
    FnDoc { path: "leviathan.fs.parent", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.basename", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.stem", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.extension", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.join", params: &[ParamDoc { name: "a", ty: "string", doc: "" }, ParamDoc { name: "b", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.relative_to", params: &[ParamDoc { name: "path", ty: "string", doc: "" }, ParamDoc { name: "base", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.with_extension", params: &[ParamDoc { name: "path", ty: "string", doc: "" }, ParamDoc { name: "ext", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.with_file_name", params: &[ParamDoc { name: "path", ty: "string", doc: "" }, ParamDoc { name: "name", ty: "string", doc: "" }], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.cwd", params: &[], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.home", params: &[], returns: "string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.temp_dir", params: &[], returns: "string", doc: "" },
    FnDoc { path: "leviathan.fs.config_dir", params: &[], returns: "string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.cache_dir", params: &[], returns: "string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.data_dir", params: &[], returns: "string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.state_dir", params: &[], returns: "string|nil", doc: "" },
    FnDoc { path: "leviathan.fs.canonicalize", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "string|nil, string|nil", doc: "" },

    FnDoc { path: "leviathan.env.get", params: &[ParamDoc { name: "name", ty: "string", doc: "" }], returns: "string|nil, string|nil", doc: "Read env var. Returns (value, nil) or (nil, err)." },
    FnDoc { path: "leviathan.env.list", params: &[], returns: "table<string, string>", doc: "List all environment variables." },

    FnDoc {
        path: "leviathan.api.create_autocmd",
        params: &[
            ParamDoc { name: "events", ty: "string[]", doc: "List of event names to subscribe to." },
            ParamDoc { name: "opts", ty: "{ callback: fun(event: string) }", doc: "" },
        ],
        returns: "",
        doc: "Subscribe to host events. Callback fires once per event firing.",
    },

    FnDoc { path: "leviathan.ui.list_regions", params: &[], returns: "string[]", doc: "List names of registered UI regions." },
    FnDoc { path: "leviathan.ui.region", params: &[ParamDoc { name: "name", ty: "string", doc: "" }], returns: "table", doc: "Look up a region handle by name." },
    FnDoc {
        path: "leviathan.ui.register_screen",
        params: &[ParamDoc {
            name: "spec",
            ty: "{ id: string, init: fun(), view: fun(), update: fun() }",
            doc: "",
        }],
        returns: "",
        doc: "Register a screen with init/view/update lifecycle callbacks.",
    },

    FnDoc { path: "leviathan.tab_registry.add", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "", doc: "Open a new tab for the given path." },
    FnDoc { path: "leviathan.tab_registry.remove", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "", doc: "Close the tab at path." },
    FnDoc { path: "leviathan.tab_registry.select", params: &[ParamDoc { name: "path", ty: "string", doc: "" }], returns: "", doc: "Focus the tab at path." },
    FnDoc { path: "leviathan.tab_registry.reorder", params: &[ParamDoc { name: "paths", ty: "string[]", doc: "" }], returns: "", doc: "Reorder tabs to match the given path list." },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stub_for_fs_read_file_present() {
        let s = emit_stubs();
        assert!(s.contains("---@class leviathan.fs"));
        assert!(s.contains("function leviathan.fs.read_file(path) end"));
        assert!(s.contains("---@param path string"));
    }

    #[test]
    fn stub_includes_all_regions() {
        let s = emit_stubs();
        for region in ["main_bar", "tab_bar", "repository"] {
            let needle = format!("function leviathan.ui.{region}.add(spec) end");
            assert!(s.contains(&needle), "missing {needle}");
        }
    }

    #[test]
    fn stub_documents_repository_class() {
        let s = emit_stubs();
        assert!(s.contains("---@class leviathan.repository"));
        assert!(s.contains("---@field name string"));
        assert!(s.contains("---@field current_branch_name string"));
    }

    #[test]
    fn stub_for_log_present() {
        let s = emit_stubs();
        assert!(s.contains("function leviathan.log(message) end"));
    }
}
