use std::collections::BTreeMap;
use std::path::Path;

use git_leviathan_plugin_api::schema::stubs;
use git_leviathan_plugin_api::schema::stubs::{FnDoc, CLASSES, FUNCTIONS};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(String::as_str) {
        Some("gen-stubs") => gen_stubs(),
        Some("gen-docs") => gen_docs(),
        _ => {
            eprintln!("usage: cargo xtask <gen-stubs|gen-docs>");
            std::process::exit(2);
        }
    }
}

fn gen_stubs() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = Path::new("target/plugin-stubs");
    std::fs::create_dir_all(out_dir)?;
    let path = out_dir.join("leviathan.lua");
    let content = stubs::emit_stubs();
    std::fs::write(&path, content)?;
    println!("wrote {}", path.display());
    Ok(())
}

fn gen_docs() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = Path::new("docs/plugins/api");
    std::fs::create_dir_all(out_dir)?;

    let mut by_ns: BTreeMap<String, Vec<&'static FnDoc>> = BTreeMap::new();
    for f in FUNCTIONS {
        let parts: Vec<&str> = f.path.split('.').collect();
        let ns = if parts.len() == 2 {
            "_root".to_string()
        } else {
            parts[1].to_string()
        };
        by_ns.entry(ns).or_default().push(f);
    }

    // Ensure "ui" namespace exists even if no top-level ui functions.
    by_ns.entry("ui".to_string()).or_default();

    // Ensure every documented class also gets a page (e.g. repository, which
    // has fields but no top-level functions).
    for cls in CLASSES {
        if let Some(rest) = cls.name.strip_prefix("leviathan.") {
            by_ns.entry(rest.to_string()).or_default();
        }
    }

    let mut ui_extras: Vec<String> = Vec::new();
    for region in git_leviathan_plugin_api::descriptor::region::REGIONS.iter() {
        for verb in ["add", "remove", "replace"] {
            ui_extras.push(format!(
                "### `leviathan.ui.{}.{}(...)`\n\nRegion-handle method, see Region Handle docs.\n",
                region.name, verb
            ));
        }
    }

    for (ns, fns) in &by_ns {
        let mut out = String::new();
        let title = if ns == "_root" {
            "leviathan (root)".to_string()
        } else {
            format!("leviathan.{ns}")
        };
        out.push_str(&format!(
            "# {title}\n\nAuto-generated by `cargo xtask gen-docs`. Do not edit by hand.\n\n"
        ));

        let class_name = format!("leviathan.{ns}");
        if let Some(cls) = CLASSES.iter().find(|c| c.name == class_name) {
            if !cls.fields.is_empty() {
                out.push_str("## Fields\n\n");
                for (n, t, doc) in cls.fields {
                    out.push_str(&format!("- `{n}` (`{t}`)"));
                    if !doc.is_empty() {
                        out.push_str(&format!(" — {doc}"));
                    }
                    out.push('\n');
                }
                out.push('\n');
            }
        }

        out.push_str("## Functions\n\n");
        if fns.is_empty() {
            out.push_str("_No top-level functions._\n\n");
        }
        for f in fns {
            let param_names: Vec<&str> = f.params.iter().map(|p| p.name).collect();
            out.push_str(&format!(
                "### `{}({})`\n\n",
                f.path,
                param_names.join(", ")
            ));
            if !f.doc.is_empty() {
                out.push_str(&format!("{}\n\n", f.doc));
            }
            if !f.params.is_empty() {
                out.push_str("**Parameters:**\n");
                for p in f.params {
                    out.push_str(&format!("- `{}` (`{}`)", p.name, p.ty));
                    if !p.doc.is_empty() {
                        out.push_str(&format!(" — {}", p.doc));
                    }
                    out.push('\n');
                }
                out.push('\n');
            }
            if !f.returns.is_empty() {
                out.push_str(&format!("**Returns:** `{}`\n\n", f.returns));
            }
        }

        if ns == "ui" {
            out.push_str("## Region Handles\n\n");
            for line in &ui_extras {
                out.push_str(line);
                out.push('\n');
            }
        }

        let filename = if ns == "_root" {
            "root.md".to_string()
        } else {
            format!("{ns}.md")
        };
        std::fs::write(out_dir.join(&filename), out)?;
    }

    println!("wrote docs to {}", out_dir.display());
    Ok(())
}
