mod acceptance;
mod api_boundary;
mod async_runtime;
mod autocmd_events;
mod capability_grants;
mod commands_palette;
mod dependency_lockfile;
mod devtools;
pub mod diagnostics;
mod extension_points;
pub mod harness;
mod keymaps;
mod lazy_loading;
mod performance_budgets;
mod persistence_settings;
mod plugin_services;
mod reload_transactions;
mod repository_git_api;
mod resource_lifecycle;
mod runtime_path;
mod widget_ast_fuzz;
mod widget_ast_snapshot;
